### ISSUE TITLE
Make it easier to discover RPC endpoints and their arguments

### ISSUE THREAD

**Issue by maurelian** [ConsenSys/Legions#16]
I think the idea would be to have all the RPC endpoints natively supported as commands. 
But a good middle ground for now would be just to have an option under `query commands list` that prints all the endpoints and their arguments.

**Comment by shayanb** [comment]
Good feature, although based on the deme I saw today for The Toaster by Dominik, I think I'll wait for him to release it and use it as the main library for RPC endpoints. It was more comprehensive

**Comment by maurelian** [comment]
Are we sunsetting Legions then? 
RPC endpoints seems like a pretty crucial feature for a ethereum network security tool.

@dmuhs, are you familiar with Legions? Do you have thoughts on how it should relate to Toaster?

**Comment by dmuhs** [comment]
@maurelian @shayanb The gist I got from the demo was that security-related RPC checks can be handled by the Toaster - basically integrating it into Legions as a library. The Toaster code itself does not provide the functionality Legions does - an interactive shell, ENS resolution, and in general poking around. It's more of a metasploit "check this, and be (un)intrusive" kind of thing.
